#!/bin/bash
# resolve links - $0 may be a softlink
if [ -z "$APP_HOME" ];then
  PRG="$0"
  while [ -h "$PRG" ] ; do
    ls=$(ls -ld "$PRG")
    link=$(expr "$ls" : '.*-> \(.*\)$')
    if expr "$link" : '/.*' > /dev/null; then
      PRG="$link"
    else
      PRG=$(dirname "$PRG")/"$link"
    fi
  done
  cd "$(dirname "$PRG")/.." || exit 1
  APP_HOME="$(pwd)"
  export APP_HOME
  cd - &>/dev/null || exit 1
fi

. "$APP_HOME"/sbin/env.sh

printf "Configuring topics..."
ssh "$USER_KAFKA"@"${NODES[0]}" "$KAFKA_BIN_DIR"/kafka-topics.sh --create --topic fds.transactions    --partitions $(( WORKERS_PER_TOPIC * 1 )) --config min.insync.replicas=1 --replication-factor 1 --bootstrap-server localhost:9092
ssh "$USER_KAFKA"@"${NODES[0]}" "$KAFKA_BIN_DIR"/kafka-topics.sh --create --topic fds.detections      --partitions $(( WORKERS_PER_TOPIC * 1 )) --config min.insync.replicas=1 --replication-factor 1 --bootstrap-server localhost:9092
echo "OK"
