#!/bin/bash
# resolve links - $0 may be a softlink
if [ -z "$APP_HOME" ];then
  PRG="$0"
  while [ -h "$PRG" ] ; do
    ls=$(ls -ld "$PRG")
    link=$(expr "$ls" : '.*-> \(.*\)$')
    if expr "$link" : '/.*' > /dev/null; then
      PRG="$link"
    else
      PRG=$(dirname "$PRG")/"$link"
    fi
  done
  cd "$(dirname "$PRG")/.." || exit 1
  APP_HOME="$(pwd)"
  export APP_HOME
  cd - &>/dev/null || exit 1
fi

. "$APP_HOME"/sbin/env.sh

printf "Starting nodes..."
for ((i=0 ; i<${#NODES[@]} ; ++i )); do
  NODE=${NODES[$i]}
  ssh "$USER_KAFKA"@"$NODE" nohup "$KAFKA_HOME"/bin/kafka-server-start.sh -daemon "$KAFKA_CONFIG"
done
echo "OK"